const elementColors = {
	'Fully online': '#277DA1',
	'Can be completed online': '#58B4D1',
	'Online exam': '#71d9cd',
	'Online discussion forum': '#58B085',
	'Lecture recordings': '#338252',
	'Online or hybrid lectures': '#7bd160',
	'MyCourses exercises': '#90be6d',
	'Educational videos': '#43AA8B',
	'Educational podcast': '#4D908E',
	'Online game': '#577590',
	'360° learning environment': '#5E60CE',
	'Aalto OpenLearning': '#8472BB',
	'FitTech': '#A25CD9',
	'A+': '#BD71A9',
	'Own site for exercises': '#EC8385',
	'TIM exercises': '#E75355',
	'MyFinanceLab exercises': '#AD3121',
	'MasteringPhysics exercises': '#DB623D',
	'Jupyter notebooks': '#f3722c',
	'Perusall': '#f8961e',
	'Aalto digital design guide': '#F9C74F',
	'Virtual laboratory': '#EDE845',

};



const elementSecondaryColors = {
	'Fully online': '#E9F4FF',
	'Can be completed online': '#16424F',
	'Online exam': '#1d4540',
	'Online discussion forum': '#163024',
	'Online or hybrid lectures': '#204016',
	'Lecture recordings': '#F2FDF6',
	'MyCourses exercises': '#3D4734',
	'Educational videos': '#1B3634',
	'Educational podcast': '#0E2020',
	'Online game': '#E8F4FF',
	'360° learning environment': '#F1ECFF',
	'Aalto OpenLearning': '#130B21',
	'FitTech': '#180A24',
	'A+': '#36162D',
	'Own site for exercises': '#4f2526',
	'TIM exercises': '#301010',
	'MyFinanceLab exercises': '#dbd0ce',
	'MasteringPhysics exercises': '#29130c',
	'Jupyter notebooks': '#422B1E',
	'Perusall': '#4D3E2C',
	'Aalto digital design guide': '#61553A',
	'Virtual laboratory': '#383719',
};

const elementTextColors = {
	'Fully online': '#fff',
	'Can be completed online': '#000',
	'Online exam': '#000',
	'Online discussion forum': '#000',
	'Online or hybrid lectures': '#000',
	'Lecture recordings': '#fff',
	'MyCourses exercises': '#000',
	'Educational videos': '#000',
	'Educational podcast': '#000',
	'Online game': '#fff',
	'360° learning environment': '#fff',
	'Aalto OpenLearning': '#fff',
	'FitTech': '#000',
	'A+': '#000',
	'Own site for exercises': '#000',
	'TIM exercises': '#000',
	'MyFinanceLab exercises': '#fff',
	'MasteringPhysics exercises': '#000',
	'Jupyter notebooks': '#000',
	'Perusall': '#000',
	'Aalto digital design guide': '#000',
	'Virtual laboratory': '#000',
};

const elementAmounts = {
	'MyCourses exercises': 0,
	'A+': 0,
	'Lecture recordings': 0,
	'Fully online': 0,
	'Online discussion forum': 0,
	'Online or hybrid lectures': 0,
	'Jupyter notebooks': 0,
	'FitTech': 0,
	'Own site for exercises': 0,
	'MyFinanceLab exercises': 0,
	'TIM exercises': 0,
	'Can be completed online': 0,
	'Online exam': 0,
	'MasteringPhysics exercises': 0,
	'Online game': 0,
	'Educational videos': 0,
	'Aalto digital design guide': 0,
	'Perusall': 0,
	'Educational podcast': 0,
	'360° learning environment': 0,
	'Virtual laboratory': 0,
	'Aalto OpenLearning': 0,
};

const elementHelperTexts = {
	'MyCourses exercises': 'Interactive exercises that provide immediate feedback to the student, such as quizzes and STACK exercises',
	'Online discussion forum': 'Interactive platform for communication, such as Zulip, Teams and Miro',
	'Online or hybrid lectures': 'Over half of the lectures are hybrid or online',
	'Lecture recordings': 'Old or current lecture recordings of at least half of the lectures',
};

export { elementColors, elementTextColors, elementAmounts, elementSecondaryColors, elementHelperTexts };